import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API='/api';
function App(){
 const [token,setToken]=useState(localStorage.getItem('token')); const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'',email:'demo@example.com',password:'Password@123'}); const [products,setProducts]=useState([]); const [product,setProduct]=useState({name:'',price:''}); const [error,setError]=useState('');
 const auth=async()=>{setError('');const url=mode==='login'?'/auth/login':'/auth/register';const r=await fetch(API+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return setError(d.message||'Request failed');localStorage.setItem('token',d.token);setToken(d.token)};
 const load=async()=>{const r=await fetch(API+'/products',{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(r.ok)setProducts(d);else setError(d.message||'Unable to load products')};
 useEffect(()=>{if(token)load()},[token]);
 const add=async()=>{const r=await fetch(API+'/products',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({name:product.name,price:Number(product.price)})});if(r.ok){setProduct({name:'',price:''});load()}else{const d=await r.json();setError(d.message)}};
 const logout=()=>{localStorage.removeItem('token');setToken(null);setProducts([])};
 if(!token)return <main className="card auth"><h1>Full Stack POC</h1><p>.NET API + React + MongoDB + JWT</p><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>{mode==='login'?null:null}<input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button onClick={auth}>{mode==='login'?'Login':'Register'}</button><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create account':'Back to login'}</button></main>;
 return <main><header><div><h1>Product Dashboard</h1><small>JWT protected API</small></div><button onClick={logout}>Logout</button></header><section className="card form"><input placeholder="Product name" value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/><input type="number" placeholder="Price" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/><button onClick={add}>Add Product</button></section>{error&&<div className="error">{error}</div>}<section className="grid">{products.map(p=><article className="card" key={p.id}><h3>{p.name}</h3><strong>₹ {p.price}</strong><small>{new Date(p.createdAt).toLocaleString()}</small></article>)}</section></main>;
}createRoot(document.getElementById('root')).render(<App/>);
